#!/bin/bash

#PBS -N assn04.8
#PBS -q debug12core
#PBS -j oe
#PBS -m abe
#PBS -M jboyko@uark.edu
#PBS -o boyko_assn04.8.out
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:00:15:00

cd /storage/jboyko/watermelon_files

module load blast/2.6.0+

blastn -query watermelon.fsa -db watermelon.fsa -outfmt 6 > ../homework/job8a.txt
blastn -dust yes -word_size 9 -reward 2 -penalty -3 -gapopen 5 -gapextend 2 -query watermelon.fsa -db watermelon.fsa -outfmt 6 > ../homework/job8b.txt
blastn -dust yes -word_size 7 -reward 5 -penalty -4 -gapopen 8 -gapextend 6 -query watermelon.fsa -db watermelon.fsa -outfmt 6 > ../homework/job8c.txt

